//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesSOAP
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuardarFacturaVentaSolicitud", Namespace="http://tempuri.org/")]
    public partial class GuardarFacturaVentaSolicitud : object
    {
        
        private WebServicesSOAP.Factura FacturaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebServicesSOAP.Factura Factura
        {
            get
            {
                return this.FacturaField;
            }
            set
            {
                this.FacturaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Factura", Namespace="http://tempuri.org/")]
    public partial class Factura : object
    {
        
        private int IdFacturaField;
        
        private System.DateTime FechaField;
        
        private int IdClienteField;
        
        private WebServicesSOAP.Venta[] DetalleVentasField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdFactura
        {
            get
            {
                return this.IdFacturaField;
            }
            set
            {
                this.IdFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WebServicesSOAP.Venta[] DetalleVentas
        {
            get
            {
                return this.DetalleVentasField;
            }
            set
            {
                this.DetalleVentasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venta", Namespace="http://tempuri.org/")]
    public partial class Venta : object
    {
        
        private int IdVentaField;
        
        private int IdFacturaField;
        
        private int IdProductoField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdVenta
        {
            get
            {
                return this.IdVentaField;
            }
            set
            {
                this.IdVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int IdFactura
        {
            get
            {
                return this.IdFacturaField;
            }
            set
            {
                this.IdFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdProducto
        {
            get
            {
                return this.IdProductoField;
            }
            set
            {
                this.IdProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CamposGenericosRespuesta", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServicesSOAP.GuardarFacturaVentaRespuesta))]
    public partial class CamposGenericosRespuesta : object
    {
        
        private string EstadoField;
        
        private string DescripcionErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DescripcionError
        {
            get
            {
                return this.DescripcionErrorField;
            }
            set
            {
                this.DescripcionErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuardarFacturaVentaRespuesta", Namespace="http://tempuri.org/")]
    public partial class GuardarFacturaVentaRespuesta : WebServicesSOAP.CamposGenericosRespuesta
    {
        
        private int NumeroFacturaField;
        
        private int CantidadDetalleVentaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroFactura
        {
            get
            {
                return this.NumeroFacturaField;
            }
            set
            {
                this.NumeroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int CantidadDetalleVenta
        {
            get
            {
                return this.CantidadDetalleVentaField;
            }
            set
            {
                this.CantidadDetalleVentaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServicesSOAP.SegundoParcialSoap")]
    public interface SegundoParcialSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento guardarFacturaVentaSolicitud del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarFacturaVenta", ReplyAction="*")]
        WebServicesSOAP.GuardarFacturaVentaResponse GuardarFacturaVenta(WebServicesSOAP.GuardarFacturaVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarFacturaVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServicesSOAP.GuardarFacturaVentaResponse> GuardarFacturaVentaAsync(WebServicesSOAP.GuardarFacturaVentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerProductosPorIdProveedorResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductosPorIdProveedor", ReplyAction="*")]
        WebServicesSOAP.ObtenerProductosPorIdProveedorResponse ObtenerProductosPorIdProveedor(WebServicesSOAP.ObtenerProductosPorIdProveedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerProductosPorIdProveedor", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServicesSOAP.ObtenerProductosPorIdProveedorResponse> ObtenerProductosPorIdProveedorAsync(WebServicesSOAP.ObtenerProductosPorIdProveedorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerCategoriasResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCategorias", ReplyAction="*")]
        WebServicesSOAP.ObtenerCategoriasResponse ObtenerCategorias(WebServicesSOAP.ObtenerCategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCategorias", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServicesSOAP.ObtenerCategoriasResponse> ObtenerCategoriasAsync(WebServicesSOAP.ObtenerCategoriasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerClientesPorIdProductoVentaResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerClientesPorIdProductoVenta", ReplyAction="*")]
        WebServicesSOAP.ObtenerClientesPorIdProductoVentaResponse ObtenerClientesPorIdProductoVenta(WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerClientesPorIdProductoVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServicesSOAP.ObtenerClientesPorIdProductoVentaResponse> ObtenerClientesPorIdProductoVentaAsync(WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarFacturaVentaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarFacturaVenta", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesSOAP.GuardarFacturaVentaRequestBody Body;
        
        public GuardarFacturaVentaRequest()
        {
        }
        
        public GuardarFacturaVentaRequest(WebServicesSOAP.GuardarFacturaVentaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarFacturaVentaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServicesSOAP.GuardarFacturaVentaSolicitud guardarFacturaVentaSolicitud;
        
        public GuardarFacturaVentaRequestBody()
        {
        }
        
        public GuardarFacturaVentaRequestBody(WebServicesSOAP.GuardarFacturaVentaSolicitud guardarFacturaVentaSolicitud)
        {
            this.guardarFacturaVentaSolicitud = guardarFacturaVentaSolicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarFacturaVentaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarFacturaVentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesSOAP.GuardarFacturaVentaResponseBody Body;
        
        public GuardarFacturaVentaResponse()
        {
        }
        
        public GuardarFacturaVentaResponse(WebServicesSOAP.GuardarFacturaVentaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarFacturaVentaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServicesSOAP.GuardarFacturaVentaRespuesta GuardarFacturaVentaResult;
        
        public GuardarFacturaVentaResponseBody()
        {
        }
        
        public GuardarFacturaVentaResponseBody(WebServicesSOAP.GuardarFacturaVentaRespuesta GuardarFacturaVentaResult)
        {
            this.GuardarFacturaVentaResult = GuardarFacturaVentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductosPorIdProveedorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductosPorIdProveedor", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesSOAP.ObtenerProductosPorIdProveedorRequestBody Body;
        
        public ObtenerProductosPorIdProveedorRequest()
        {
        }
        
        public ObtenerProductosPorIdProveedorRequest(WebServicesSOAP.ObtenerProductosPorIdProveedorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductosPorIdProveedorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProveedor;
        
        public ObtenerProductosPorIdProveedorRequestBody()
        {
        }
        
        public ObtenerProductosPorIdProveedorRequestBody(int idProveedor)
        {
            this.idProveedor = idProveedor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerProductosPorIdProveedorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerProductosPorIdProveedorResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesSOAP.ObtenerProductosPorIdProveedorResponseBody Body;
        
        public ObtenerProductosPorIdProveedorResponse()
        {
        }
        
        public ObtenerProductosPorIdProveedorResponse(WebServicesSOAP.ObtenerProductosPorIdProveedorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerProductosPorIdProveedorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ObtenerProductosPorIdProveedorResult;
        
        public ObtenerProductosPorIdProveedorResponseBody()
        {
        }
        
        public ObtenerProductosPorIdProveedorResponseBody(System.Xml.XmlElement ObtenerProductosPorIdProveedorResult)
        {
            this.ObtenerProductosPorIdProveedorResult = ObtenerProductosPorIdProveedorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCategoriasRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCategorias", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesSOAP.ObtenerCategoriasRequestBody Body;
        
        public ObtenerCategoriasRequest()
        {
        }
        
        public ObtenerCategoriasRequest(WebServicesSOAP.ObtenerCategoriasRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerCategoriasRequestBody
    {
        
        public ObtenerCategoriasRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCategoriasResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCategoriasResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesSOAP.ObtenerCategoriasResponseBody Body;
        
        public ObtenerCategoriasResponse()
        {
        }
        
        public ObtenerCategoriasResponse(WebServicesSOAP.ObtenerCategoriasResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCategoriasResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ObtenerCategoriasResult;
        
        public ObtenerCategoriasResponseBody()
        {
        }
        
        public ObtenerCategoriasResponseBody(System.Xml.XmlElement ObtenerCategoriasResult)
        {
            this.ObtenerCategoriasResult = ObtenerCategoriasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClientesPorIdProductoVentaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerClientesPorIdProductoVenta", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequestBody Body;
        
        public ObtenerClientesPorIdProductoVentaRequest()
        {
        }
        
        public ObtenerClientesPorIdProductoVentaRequest(WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerClientesPorIdProductoVentaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idProducto;
        
        public ObtenerClientesPorIdProductoVentaRequestBody()
        {
        }
        
        public ObtenerClientesPorIdProductoVentaRequestBody(int idProducto)
        {
            this.idProducto = idProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerClientesPorIdProductoVentaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerClientesPorIdProductoVentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesSOAP.ObtenerClientesPorIdProductoVentaResponseBody Body;
        
        public ObtenerClientesPorIdProductoVentaResponse()
        {
        }
        
        public ObtenerClientesPorIdProductoVentaResponse(WebServicesSOAP.ObtenerClientesPorIdProductoVentaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerClientesPorIdProductoVentaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement ObtenerClientesPorIdProductoVentaResult;
        
        public ObtenerClientesPorIdProductoVentaResponseBody()
        {
        }
        
        public ObtenerClientesPorIdProductoVentaResponseBody(System.Xml.XmlElement ObtenerClientesPorIdProductoVentaResult)
        {
            this.ObtenerClientesPorIdProductoVentaResult = ObtenerClientesPorIdProductoVentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SegundoParcialSoapChannel : WebServicesSOAP.SegundoParcialSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SegundoParcialSoapClient : System.ServiceModel.ClientBase<WebServicesSOAP.SegundoParcialSoap>, WebServicesSOAP.SegundoParcialSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SegundoParcialSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SegundoParcialSoapClient.GetBindingForEndpoint(endpointConfiguration), SegundoParcialSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SegundoParcialSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SegundoParcialSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SegundoParcialSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SegundoParcialSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SegundoParcialSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServicesSOAP.GuardarFacturaVentaResponse WebServicesSOAP.SegundoParcialSoap.GuardarFacturaVenta(WebServicesSOAP.GuardarFacturaVentaRequest request)
        {
            return base.Channel.GuardarFacturaVenta(request);
        }
        
        public WebServicesSOAP.GuardarFacturaVentaRespuesta GuardarFacturaVenta(WebServicesSOAP.GuardarFacturaVentaSolicitud guardarFacturaVentaSolicitud)
        {
            WebServicesSOAP.GuardarFacturaVentaRequest inValue = new WebServicesSOAP.GuardarFacturaVentaRequest();
            inValue.Body = new WebServicesSOAP.GuardarFacturaVentaRequestBody();
            inValue.Body.guardarFacturaVentaSolicitud = guardarFacturaVentaSolicitud;
            WebServicesSOAP.GuardarFacturaVentaResponse retVal = ((WebServicesSOAP.SegundoParcialSoap)(this)).GuardarFacturaVenta(inValue);
            return retVal.Body.GuardarFacturaVentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServicesSOAP.GuardarFacturaVentaResponse> WebServicesSOAP.SegundoParcialSoap.GuardarFacturaVentaAsync(WebServicesSOAP.GuardarFacturaVentaRequest request)
        {
            return base.Channel.GuardarFacturaVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServicesSOAP.GuardarFacturaVentaResponse> GuardarFacturaVentaAsync(WebServicesSOAP.GuardarFacturaVentaSolicitud guardarFacturaVentaSolicitud)
        {
            WebServicesSOAP.GuardarFacturaVentaRequest inValue = new WebServicesSOAP.GuardarFacturaVentaRequest();
            inValue.Body = new WebServicesSOAP.GuardarFacturaVentaRequestBody();
            inValue.Body.guardarFacturaVentaSolicitud = guardarFacturaVentaSolicitud;
            return ((WebServicesSOAP.SegundoParcialSoap)(this)).GuardarFacturaVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServicesSOAP.ObtenerProductosPorIdProveedorResponse WebServicesSOAP.SegundoParcialSoap.ObtenerProductosPorIdProveedor(WebServicesSOAP.ObtenerProductosPorIdProveedorRequest request)
        {
            return base.Channel.ObtenerProductosPorIdProveedor(request);
        }
        
        public System.Xml.XmlElement ObtenerProductosPorIdProveedor(int idProveedor)
        {
            WebServicesSOAP.ObtenerProductosPorIdProveedorRequest inValue = new WebServicesSOAP.ObtenerProductosPorIdProveedorRequest();
            inValue.Body = new WebServicesSOAP.ObtenerProductosPorIdProveedorRequestBody();
            inValue.Body.idProveedor = idProveedor;
            WebServicesSOAP.ObtenerProductosPorIdProveedorResponse retVal = ((WebServicesSOAP.SegundoParcialSoap)(this)).ObtenerProductosPorIdProveedor(inValue);
            return retVal.Body.ObtenerProductosPorIdProveedorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServicesSOAP.ObtenerProductosPorIdProveedorResponse> WebServicesSOAP.SegundoParcialSoap.ObtenerProductosPorIdProveedorAsync(WebServicesSOAP.ObtenerProductosPorIdProveedorRequest request)
        {
            return base.Channel.ObtenerProductosPorIdProveedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServicesSOAP.ObtenerProductosPorIdProveedorResponse> ObtenerProductosPorIdProveedorAsync(int idProveedor)
        {
            WebServicesSOAP.ObtenerProductosPorIdProveedorRequest inValue = new WebServicesSOAP.ObtenerProductosPorIdProveedorRequest();
            inValue.Body = new WebServicesSOAP.ObtenerProductosPorIdProveedorRequestBody();
            inValue.Body.idProveedor = idProveedor;
            return ((WebServicesSOAP.SegundoParcialSoap)(this)).ObtenerProductosPorIdProveedorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServicesSOAP.ObtenerCategoriasResponse WebServicesSOAP.SegundoParcialSoap.ObtenerCategorias(WebServicesSOAP.ObtenerCategoriasRequest request)
        {
            return base.Channel.ObtenerCategorias(request);
        }
        
        public System.Xml.XmlElement ObtenerCategorias()
        {
            WebServicesSOAP.ObtenerCategoriasRequest inValue = new WebServicesSOAP.ObtenerCategoriasRequest();
            inValue.Body = new WebServicesSOAP.ObtenerCategoriasRequestBody();
            WebServicesSOAP.ObtenerCategoriasResponse retVal = ((WebServicesSOAP.SegundoParcialSoap)(this)).ObtenerCategorias(inValue);
            return retVal.Body.ObtenerCategoriasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServicesSOAP.ObtenerCategoriasResponse> WebServicesSOAP.SegundoParcialSoap.ObtenerCategoriasAsync(WebServicesSOAP.ObtenerCategoriasRequest request)
        {
            return base.Channel.ObtenerCategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServicesSOAP.ObtenerCategoriasResponse> ObtenerCategoriasAsync()
        {
            WebServicesSOAP.ObtenerCategoriasRequest inValue = new WebServicesSOAP.ObtenerCategoriasRequest();
            inValue.Body = new WebServicesSOAP.ObtenerCategoriasRequestBody();
            return ((WebServicesSOAP.SegundoParcialSoap)(this)).ObtenerCategoriasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServicesSOAP.ObtenerClientesPorIdProductoVentaResponse WebServicesSOAP.SegundoParcialSoap.ObtenerClientesPorIdProductoVenta(WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequest request)
        {
            return base.Channel.ObtenerClientesPorIdProductoVenta(request);
        }
        
        public System.Xml.XmlElement ObtenerClientesPorIdProductoVenta(int idProducto)
        {
            WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequest inValue = new WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequest();
            inValue.Body = new WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequestBody();
            inValue.Body.idProducto = idProducto;
            WebServicesSOAP.ObtenerClientesPorIdProductoVentaResponse retVal = ((WebServicesSOAP.SegundoParcialSoap)(this)).ObtenerClientesPorIdProductoVenta(inValue);
            return retVal.Body.ObtenerClientesPorIdProductoVentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServicesSOAP.ObtenerClientesPorIdProductoVentaResponse> WebServicesSOAP.SegundoParcialSoap.ObtenerClientesPorIdProductoVentaAsync(WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequest request)
        {
            return base.Channel.ObtenerClientesPorIdProductoVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServicesSOAP.ObtenerClientesPorIdProductoVentaResponse> ObtenerClientesPorIdProductoVentaAsync(int idProducto)
        {
            WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequest inValue = new WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequest();
            inValue.Body = new WebServicesSOAP.ObtenerClientesPorIdProductoVentaRequestBody();
            inValue.Body.idProducto = idProducto;
            return ((WebServicesSOAP.SegundoParcialSoap)(this)).ObtenerClientesPorIdProductoVentaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SegundoParcialSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SegundoParcialSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SegundoParcialSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44390/SegundoParcial.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SegundoParcialSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44390/SegundoParcial.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SegundoParcialSoap,
            
            SegundoParcialSoap12,
        }
    }
}
