-- Ingresar al esquema PROVEEDOR_LEADS_4
ALTER SESSION SET CURRENT_SCHEMA = PROVEEDOR_LEADS_4;

-- Crear la tabla CATEGORIAS
CREATE TABLE CATEGORIAS (
    ID_CATEGORIA NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(100)
);

-- Crear la tabla PROVEEDORES
CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    DIRECCION VARCHAR2(100),
    TELEFONO VARCHAR2(15)
);

-- Crear la tabla PRODUCTOS
CREATE TABLE PRODUCTOS (
    ID_PRODUCTO NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(100),
    PRECIO NUMBER,
    ID_CATEGORIA NUMBER,
    ID_PROVEEDOR NUMBER,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

-- Crear la tabla CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    DIRECCION VARCHAR2(100),
    TELEFONO VARCHAR2(15)
);

-- Crear la tabla FACTURAS
CREATE TABLE FACTURAS (
    ID_FACTURA NUMBER PRIMARY KEY,
    FECHA DATE,
    ID_CLIENTE NUMBER,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

-- Crear la tabla VENTAS
CREATE TABLE VENTAS (
    ID_VENTA NUMBER PRIMARY KEY,
    ID_FACTURA NUMBER,
    ID_PRODUCTO NUMBER,
    CANTIDAD NUMBER,
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS(ID_FACTURA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);