-- Crear la secuencia FACTURA_SEQ
CREATE SEQUENCE FACTURA_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Crear la secuencia VENTA_SEQ
CREATE SEQUENCE VENTA_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;