-- Conceder permisos al usuario PROVEEDOR_LEADS_4
GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIAS TO PROVEEDOR_LEADS_4;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROVEEDORES TO PROVEEDOR_LEADS_4;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUCTOS TO PROVEEDOR_LEADS_4;
GRANT SELECT, INSERT, UPDATE, DELETE ON CLIENTES TO PROVEEDOR_LEADS_4;
GRANT SELECT, INSERT, UPDATE, DELETE ON FACTURAS TO PROVEEDOR_LEADS_4;
GRANT SELECT, INSERT, UPDATE, DELETE ON VENTAS TO PROVEEDOR_LEADS_4;